### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by bazoni** [recombinant/petzold-pw5e#1]
Hi there!

You did an amazing work, as I go trough the book I will probably make some adjustments, such as compile with /W4 flag and and make compilation as smooth as possible.

also some projects are missing include files (ex: sysmets 3 depends on sysmets 2 and 1 include)

do you have some general suggestions to focus on?

**Comment by recombinant** [comment]
Thank Charles Petzold! 

If you want to focus on something be aware that much the book's code was originally written for 16 bit Windows 3.0/3.1 (long gone), then ported to 32 bit - now we have 64 bit Windows and the API has changed subtly - the only place you will find any mention is in the documentation. Read Microsoft's own  documentation for each function. Google for *windows api SetWindowLong* for an example, or *windows api setscrollpos* for another example.

Yes, sysmets.h is required by:
- Chapter 4 - sysmets1.c, sysmets2.c & sysmets3.c
- Chapter 6 - sysmets4.c
- Chapter 7 - sysmets.c

I worked through the book using Visual Studio 2015. Now Visual Studio 2017 is available. I will not be revisiting in the near future.

(Microsoft Windows is the business platform of choice. But using C to access the API is not as popular are it once was.)
